// imports the Mongoose library, providing a straightforward way to model, validate, and interact with MongoDB documents.
const mongoose = require("mongoose");

// mongoose.Schema function is used to define the structure of a document in a MongoDB collection.
const contactSchema = mongoose.Schema(
  {
    userID: {
      //userID field will store MongoDB ObjectIds.
      //ObjectIds are unique identifiers automatically generated by MongoDB for each document.
      type: mongoose.Schema.Types.ObjectId,

      //userID field is required and must be provided else it will fail validation.
      required: [true, "Please provide userID"],

      //reference to another Mongoose model, in this case, the "User" model.
      //It establishes a relationship between the current schema and the "User" model
      // ref: "User",
    },
    name: {
      type: String,

      //[true, "Please add name of contact"] syntax is used to provide a custom error message if the validation fails.
      required: [true, "Please add name of contact"],
    },
    mobile: {
      type: String,
      required: [true, "Please add mobile number of contact"],
    },
    email: {
      type: String,
      required: [true, "Please add email address of contact"],
    },
  },
  {
    timestamps: true,
  }
);

//exporting Mongoose model named "Contact" based on the contactSchema
module.exports = mongoose.model("Contact", contactSchema);
